### PR TITLE
Creation of Customer Model

### PR DESCRIPTION
**Pull request by Shu52**
# Creation of Customer Model
# Description
 Created Customer Model for # 1, will still need to create the controller for the issue. Property LastLogin is not tracked or modified in other issues of tickets. It is okay to leave the value that reflects account creation. This model is dependent on Product and PaymentType models and is needed for Product, Order and CustomerPayment.
 Fixes  (#1 )
 ## Type of change
 Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)
 # Testing Instructions
-Ensure that Product.cs and PaymentType.cs is included in the Model folder

 -In the directory BangazonAPI, use command "dotnet run" to run program. The server should then start and run without errors.

-Make sure all names line up with ERD.(https://drive.google.com/file/d/1Qo9O2oUezNd13Wsr0_VUbUtwwDo4-oAt/view)

 # Checklist:
 - [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Shu52** [comment]
Also, let me know if the extra whitespace is an eyesore

**Comment by JoeysGithuub** [comment]
Need to merge dependent models.

**Comment by Shu52** [comment]
added PaymentTypes to pull request per Joey

**Comment by JoeysGithuub** [comment]
It works

**Pull request merged**
